name: mimic_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pymc>=5
  - tensorflow
  - gpflow>=2.9
  - arviz
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - tensorflow-io-gcs-filesystem>=0.29.0,<0.32.0
