name: mimic_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pymc>=5
  - gpflow>=2.9,<2.10  # Allow some flexibility while specifying compatibility
  - tensorflow>=2.16,<2.17  # Leave room for patch updates but stay compatible
  - tensorflow-probability>=0.24,<0.25  # Ensure compatibility but allow minor patch updates
  - pytensor
  - seaborn
  - scikit-learn
  - scipy
  - numpy
  - ipykernel
  - ipywidgets
  - pip
  - pip:
      - pytest
      - pytest-cov
      - pytest-mock
