name: mimic_env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pymc>=5
  - gpflow>=2.9
  - pytensor
  - seaborn
  - scikit-learn
  - scipy
  - numpy
  - ipykernel
  - ipywidgets
  - matplotlib
  - pandas
  - arviz
  - cloudpickle
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - pytest
      - pytest-cov
      - pytest-mock
