name: mimic_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pymc>=5,<6
  - gpflow>=2.9,<2.10
  - tensorflow>=2.16,<2.17
  - tensorflow-probability>=0.24,<0.25
  - pytensor
  - seaborn
  - scikit-learn
  - scipy
  - numpy
  - ipykernel
  - ipywidgets
  - matplotlib
  - pandas
  - arviz
  - cloudpickle
  - pip
  - pip:
      - pytest
      - pytest-cov
      - pytest-mock