name: Feature Request
description: Suggest an idea for this project.
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please fill out the following sections to propose a new feature.

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: Provide a brief summary of the feature.
      placeholder: "Brief summary of the feature"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Is your feature request related to a problem?
      description: "Describe the problem you are facing. Example: 'I'm always frustrated when...'"
      placeholder: "Describe the problem"

  - type: textarea
    id: feature-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "Describe the solution"

  - type: textarea
    id: feature-alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Describe alternatives"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Any other details or attachments?"

  - type: checkboxes
    id: optional-labels
    attributes:
      label: Optional Labels
      description: If any of these optional labels are necessary, please select them and make sure to add them from the sidebar.
      options:
        - label: HIGH priority
        - label: LOW priority
        - label: good first issue
        - label: help wanted
        - label: wontfix
        - label: question/discussion
