name: 📝 Documentation/Examples Request
description: Suggest changes or improvements to the documentation or examples.
title: "[Doc]: "
labels: ["documentation/example"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation/Examples Request
        Please fill out the following sections to suggest improvements.

  - type: input
    id: doc-example-title
    attributes:
      label: Title
      description: Provide a brief summary of the documentation or example issue.
      placeholder: "Brief summary"
    validations:
      required: true

  - type: textarea
    id: doc-example-description
    attributes:
      label: Describe the documentation/example issue
      description: A clear and concise description of the documentation problem or improvement needed.
      placeholder: "Describe the issue in detail"
    validations:
      required: true

  - type: input
    id: doc-example-location
    attributes:
      label: Location
      description: Specify where in the documentation or examples the issue is found or where the improvement should be made.
      placeholder: "Provide the location"

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: Any specific suggestions for how to improve the documentation or examples.
      placeholder: "Describe the suggested improvement"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the documentation or examples request here.
      placeholder: "Any other details or attachments?"

  - type: checkboxes
    id: optional-labels
    attributes:
      label: Optional Labels
      description: If any of these optional labels are necessary, please select them and make sure to add them from the sidebar.
      options:
        - label: HIGH priority
        - label: LOW priority
        - label: good first issue
        - label: help wanted
        - label: wontfix
        - label: question/discussion
