name: Build and Deploy Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install sphinx sphinx-rtd-theme

      - name: Generate API documentation
        run: sphinx-apidoc -o docs/source/ ./ setup.py

      - name: Build Sphinx documentation
        run: |
          cd docs
          make clean
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
