name: Test and Coverage

on:
  push:
    branches: 
      - '**'  # This runs the workflow on push to any branch
  pull_request:
    branches: 
      - '**'  # This runs the workflow on a pull request to any branch

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pip install -e .

      - name: Run tests with coverage
        run: |
          pytest --cov=mimic --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov
