name: Test and Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: mimic_env
          environment-file: environment.yml
          python-version: "3.10"

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          # Initialize conda for bash shell
          eval "$(conda shell.bash hook)"
          conda activate mimic_env
          # Install dependencies via conda
          conda install -y -c conda-forge pymc>=5 pytensor seaborn scikit-learn scipy numpy ipykernel ipywidgets
          # Install any pip-only dependencies if needed
          pip install -r requirements.txt
          # Install testing tools
          pip install pytest pytest-cov
          # Install your package in editable mode
          pip install -e .

      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          eval "$(conda shell.bash hook)"
          conda activate mimic_env
          pytest --cov=mimic --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov
