name: Test and Coverage

on:
  push:
    branches:
      - '**'  # This runs the workflow on push to any branch
  pull_request:
    branches:
      - '**'  # This runs the workflow on a pull request to any branch

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: mimic_env
          condarc-file: |
            channels:
              - conda-forge
              - defaults

      - name: Install Dependencies
        shell: bash
        run: |
          conda activate mimic_env
          # Install dependencies via conda
          conda install -c conda-forge pymc>=5 pytensor seaborn scikit-learn scipy numpy ipykernel ipywidgets
          # Install any pip-only dependencies if needed
          pip install -r requirements.txt
          # Install testing tools
          pip install pytest pytest-cov
          # Install your package in editable mode
          pip install -e .

      - name: Run tests with coverage
        shell: bash
        run: |
          conda activate mimic_env
          pytest --cov=mimic --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov
