name: Update requirements.txt on PR merge

on:
  pull_request:
    types: [closed]
    branches: 
      - master

jobs:
  update-requirements:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automatic requirements.txt for Python Project
        uses: ryan-rozario/pipreqs-action@master
        with:
          PROJECT_PATH: project_folder   # Replace with the path to your Python project
          REQUIREMENT_PATH: project_folder/requirements.txt  # Replace with your requirements.txt file path
