name: Update requirements.txt on PR merge

on:
  pull_request:
    types: [closed]
    branches: 
      - master

jobs:
  update-requirements:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automatic requirements.txt for Python Project
        uses: ryan-rozario/pipreqs-action@master
        with:
          PROJECT_PATH: ./   # Set to root of the repository
          REQUIREMENT_PATH: ./requirements.txt  # Path to requirements.txt in the root of the repository
